export const CATEGORY_COLORS = [
	'red',
	'orange',
	'amber',
	'yellow',
	'lime',
	'green',
	'emerald',
	'teal',
	'cyan',
	'sky',
	'blue',
	'indigo',
	'violet',
	'purple',
	'fuchsia',
	'pink',
	'rose',
	'slate',
] as const

export type TCategoryColor = (typeof CATEGORY_COLORS)[number]

export const CATEGORY_COLOR_LABELS: Record<TCategoryColor, string> = {
	blue: 'Blue',
	sky: 'Sky',
	cyan: 'Cyan',
	slate: 'Slate',
	teal: 'Teal',
	green: 'Green',
	lime: 'Lime',
	emerald: 'Emerald',
	red: 'Red',
	rose: 'Rose',
	yellow: 'Yellow',
	amber: 'Amber',
	orange: 'Orange',
	indigo: 'Indigo',
	violet: 'Violet',
	purple: 'Purple',
	fuchsia: 'Fuchsia',
	pink: 'Pink',
}

export const CATEGORY_DOT: Record<TCategoryColor, string> = {
	blue: 'bg-blue-500',
	sky: 'bg-sky-500',
	cyan: 'bg-cyan-500',
	slate: 'bg-slate-500',
	teal: 'bg-teal-500',
	green: 'bg-green-500',
	lime: 'bg-lime-500',
	emerald: 'bg-emerald-500',
	red: 'bg-red-500',
	rose: 'bg-rose-500',
	yellow: 'bg-yellow-500',
	amber: 'bg-amber-500',
	orange: 'bg-orange-500',
	indigo: 'bg-indigo-500',
	violet: 'bg-violet-500',
	purple: 'bg-purple-500',
	fuchsia: 'bg-fuchsia-500',
	pink: 'bg-pink-500',
}
